name: deploy-iOS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, 'release-ios')"

    steps:
    - name: Checkout project
      uses: actions/checkout@v1
      with:
        token: ${{ secrets.pat }}

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Fastlane setup
      working-directory: packages/mobile
      run: |
        sudo gem install fastlane -NV

    - name: Install node_modules
      run: |
        yarn install --frozen-lockfile

    - name: Deploy iOS & Upload to TestFlight
      working-directory: packages/mobile/ios
      env:
        MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        pat: ${{ secrets.pat }}
      run: |
        fastlane ios beta_ci
